name: be-auto-deploy
on:
  push:
    branches:
      - "main"
    paths:
      - "back_end/**"
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: checking allow to build
        run: |
          if [ ${{secrets.BUILD}} == ACTIVE ]
          then
            echo '------------------- ready to deploy --------------------'
          else
            echo 'not ready'
            exit 1
          fi

  build-push:
    needs: build-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Build and Push for Server
        uses: docker/build-push-action@v2
        id: docker_build_server
        with:
          context: ./back_end
          file: ./back_end/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/be-sep490-g61:latest
      - name: Verify
        run: |
          echo ${{steps.docker_build_server.outputs.digest}}
          echo 'Build done, ready to deploy'
